/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef MAXPHASES_H
#define MAXPHASES_H

/* function declarations */
void init_maxPhases(void);
Netsnmp_Node_Handler handle_maxPhases;

#endif /* MAXPHASES_H */
