/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.int_watch.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "maxPhases.h"

/*
 * The variables we want to tie the relevant OIDs to.
 * The agent will handle all GET and (if applicable) SET requests
 * to these variables automatically, changing the values as needed.
 */

long    maxPhases = 2;

/*
 * Our initialization routine, called automatically by the agent 
 * (Note that the function name must match init_FILENAME()) 
 */
void
init_maxPhases(void)
{
  netsnmp_handler_registration *reg;

    const oid maxPhases_oid[] = { 1,3,6,1,4,1,1206,4,2,1,1,1 };
  static netsnmp_watcher_info maxPhases_winfo;

  /*
   * a debugging statement.  Run the agent with -DmaxPhases to see
   * the output of this debugging statement. 
   */
  DEBUGMSGTL(("maxPhases", "Initializing the maxPhases module\n"));


    /*
     * Register scalar watchers for each of the MIB objects.
     * The ASN type and RO/RW status are taken from the MIB definition,
     * but can be adjusted if needed.
     *
     * In most circumstances, the scalar watcher will handle all
     * of the necessary processing.  But the NULL parameter in the
     * netsnmp_create_handler_registration() call can be used to
     * supply a user-provided handler if necessary.
     *
     * This approach can also be used to handle Counter64, string-
     * and OID-based watched scalars (although variable-sized writeable
     * objects will need some more specialised initialisation).
     */
    DEBUGMSGTL(("maxPhases",
                "Initializing maxPhases scalar integer.  Default value = %d\n",
                maxPhases));
    reg = netsnmp_create_handler_registration(
             "maxPhases", NULL,
              maxPhases_oid, OID_LENGTH(maxPhases_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&maxPhases_winfo, &maxPhases, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &maxPhases_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched maxPhases" );
    }


  DEBUGMSGTL(("maxPhases",
              "Done initalizing maxPhases module\n"));
}
