/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.int_watch.conf
 */
#ifndef MAXPHASES_H
#define MAXPHASES_H

/* function declarations */
void init_maxPhases(void);

#endif /* MAXPHASES_H */
